package pe.itland.xtreampad.bd.repositorios;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import pe.itland.xtreampad.bd.modelo.Home_Banner;
import pe.itland.xtreampad.bd.modelo.Home_Language;
import pe.itland.xtreampad.bd.modelo.Home_Menu;
import pe.itland.xtreampad.bd.modelo.Home_Principal;
import pe.itland.xtreampad.bd.modelo.Mascota;
import pe.itland.xtreampad.bd.modelo.Persona;

import pe.itland.xtreampad.bd.repositorios.Home_BannerDao;
import pe.itland.xtreampad.bd.repositorios.Home_LanguageDao;
import pe.itland.xtreampad.bd.repositorios.Home_MenuDao;
import pe.itland.xtreampad.bd.repositorios.Home_PrincipalDao;
import pe.itland.xtreampad.bd.repositorios.MascotaDao;
import pe.itland.xtreampad.bd.repositorios.PersonaDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig home_BannerDaoConfig;
    private final DaoConfig home_LanguageDaoConfig;
    private final DaoConfig home_MenuDaoConfig;
    private final DaoConfig home_PrincipalDaoConfig;
    private final DaoConfig mascotaDaoConfig;
    private final DaoConfig personaDaoConfig;

    private final Home_BannerDao home_BannerDao;
    private final Home_LanguageDao home_LanguageDao;
    private final Home_MenuDao home_MenuDao;
    private final Home_PrincipalDao home_PrincipalDao;
    private final MascotaDao mascotaDao;
    private final PersonaDao personaDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        home_BannerDaoConfig = daoConfigMap.get(Home_BannerDao.class).clone();
        home_BannerDaoConfig.initIdentityScope(type);

        home_LanguageDaoConfig = daoConfigMap.get(Home_LanguageDao.class).clone();
        home_LanguageDaoConfig.initIdentityScope(type);

        home_MenuDaoConfig = daoConfigMap.get(Home_MenuDao.class).clone();
        home_MenuDaoConfig.initIdentityScope(type);

        home_PrincipalDaoConfig = daoConfigMap.get(Home_PrincipalDao.class).clone();
        home_PrincipalDaoConfig.initIdentityScope(type);

        mascotaDaoConfig = daoConfigMap.get(MascotaDao.class).clone();
        mascotaDaoConfig.initIdentityScope(type);

        personaDaoConfig = daoConfigMap.get(PersonaDao.class).clone();
        personaDaoConfig.initIdentityScope(type);

        home_BannerDao = new Home_BannerDao(home_BannerDaoConfig, this);
        home_LanguageDao = new Home_LanguageDao(home_LanguageDaoConfig, this);
        home_MenuDao = new Home_MenuDao(home_MenuDaoConfig, this);
        home_PrincipalDao = new Home_PrincipalDao(home_PrincipalDaoConfig, this);
        mascotaDao = new MascotaDao(mascotaDaoConfig, this);
        personaDao = new PersonaDao(personaDaoConfig, this);

        registerDao(Home_Banner.class, home_BannerDao);
        registerDao(Home_Language.class, home_LanguageDao);
        registerDao(Home_Menu.class, home_MenuDao);
        registerDao(Home_Principal.class, home_PrincipalDao);
        registerDao(Mascota.class, mascotaDao);
        registerDao(Persona.class, personaDao);
    }
    
    public void clear() {
        home_BannerDaoConfig.clearIdentityScope();
        home_LanguageDaoConfig.clearIdentityScope();
        home_MenuDaoConfig.clearIdentityScope();
        home_PrincipalDaoConfig.clearIdentityScope();
        mascotaDaoConfig.clearIdentityScope();
        personaDaoConfig.clearIdentityScope();
    }

    public Home_BannerDao getHome_BannerDao() {
        return home_BannerDao;
    }

    public Home_LanguageDao getHome_LanguageDao() {
        return home_LanguageDao;
    }

    public Home_MenuDao getHome_MenuDao() {
        return home_MenuDao;
    }

    public Home_PrincipalDao getHome_PrincipalDao() {
        return home_PrincipalDao;
    }

    public MascotaDao getMascotaDao() {
        return mascotaDao;
    }

    public PersonaDao getPersonaDao() {
        return personaDao;
    }

}
